# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kosbr's blog
email: kosbr.dev@yandex.com
description: > # this means to ignore newlines until "baseurl:"
  Author: Konstantin Bryazgin - Java Developer. You are visiting my personal technical blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kosbr.guthub.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

sass:
    sass_dir: /

paginate: 8

gems: [jekyll-paginate]
